[2025-03-29T14:55:59.089+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-29T14:55:59.266+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fist_dag_v5.third_task scheduled__2024-12-24T00:00:00+00:00 [queued]>
[2025-03-29T14:55:59.403+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fist_dag_v5.third_task scheduled__2024-12-24T00:00:00+00:00 [queued]>
[2025-03-29T14:55:59.404+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-03-29T14:55:59.510+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): third_task> on 2024-12-24 00:00:00+00:00
[2025-03-29T14:55:59.543+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=317) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-29T14:55:59.549+0000] {standard_task_runner.py:72} INFO - Started process 346 to run task
[2025-03-29T14:55:59.566+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fist_dag_v5', 'third_task', 'scheduled__2024-12-24T00:00:00+00:00', '--job-id', '184', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp8fxt923c']
[2025-03-29T14:55:59.569+0000] {standard_task_runner.py:105} INFO - Job 184: Subtask third_task
[2025-03-29T14:56:00.091+0000] {task_command.py:467} INFO - Running <TaskInstance: fist_dag_v5.third_task scheduled__2024-12-24T00:00:00+00:00 [running]> on host ba06481f48a9
[2025-03-29T14:56:00.665+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='fist_dag_v5' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2024-12-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-24T00:00:00+00:00'
[2025-03-29T14:56:00.683+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-29T14:56:00.879+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-29T14:56:00.889+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello, i am task3 and will be running after task1!']
[2025-03-29T14:56:00.982+0000] {subprocess.py:99} INFO - Output:
[2025-03-29T14:56:00.989+0000] {subprocess.py:106} INFO - hello, i am task3 and will be running after task1!
[2025-03-29T14:56:01.004+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-29T14:56:01.165+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-29T14:56:01.175+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=fist_dag_v5, task_id=third_task, run_id=scheduled__2024-12-24T00:00:00+00:00, execution_date=20241224T000000, start_date=20250329T145559, end_date=20250329T145601
[2025-03-29T14:56:01.343+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-29T14:56:01.377+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
