[2025-04-06T03:34:09.489+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-06T03:34:09.526+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_python_dependencies_v01.get_sklearn scheduled__2025-04-01T00:00:00+00:00 [queued]>
[2025-04-06T03:34:09.548+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_python_dependencies_v01.get_sklearn scheduled__2025-04-01T00:00:00+00:00 [queued]>
[2025-04-06T03:34:09.550+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-04-06T03:34:09.593+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): get_sklearn> on 2025-04-01 00:00:00+00:00
[2025-04-06T03:34:09.610+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=337) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-06T03:34:09.608+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_python_dependencies_v01', 'get_sklearn', 'scheduled__2025-04-01T00:00:00+00:00', '--job-id', '896', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_python_dependencies.py', '--cfg-path', '/tmp/tmpuqxqt_cv']
[2025-04-06T03:34:09.612+0000] {standard_task_runner.py:72} INFO - Started process 339 to run task
[2025-04-06T03:34:09.612+0000] {standard_task_runner.py:105} INFO - Job 896: Subtask get_sklearn
[2025-04-06T03:34:09.724+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_python_dependencies_v01.get_sklearn scheduled__2025-04-01T00:00:00+00:00 [running]> on host 629788fdd8a2
[2025-04-06T03:34:09.962+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='acilrest12' AIRFLOW_CTX_DAG_ID='dag_with_python_dependencies_v01' AIRFLOW_CTX_TASK_ID='get_sklearn' AIRFLOW_CTX_EXECUTION_DATE='2025-04-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-01T00:00:00+00:00'
[2025-04-06T03:34:09.964+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-06T03:34:16.426+0000] {logging_mixin.py:190} INFO - sklearn version: 1.6.1
[2025-04-06T03:34:16.428+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-06T03:34:16.455+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-06T03:34:16.456+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_python_dependencies_v01, task_id=get_sklearn, run_id=scheduled__2025-04-01T00:00:00+00:00, execution_date=20250401T000000, start_date=20250406T033409, end_date=20250406T033416
[2025-04-06T03:34:16.580+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-06T03:34:16.622+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-06T03:34:16.626+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
