[2024-11-30T19:49:39.114+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-30T19:49:39.166+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fist_dag_v5.third_task manual__2024-11-30T19:49:36.293888+00:00 [queued]>
[2024-11-30T19:49:39.187+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fist_dag_v5.third_task manual__2024-11-30T19:49:36.293888+00:00 [queued]>
[2024-11-30T19:49:39.188+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2024-11-30T19:49:39.226+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): third_task> on 2024-11-30 19:49:36.293888+00:00
[2024-11-30T19:49:39.241+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=871) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-30T19:49:39.244+0000] {standard_task_runner.py:72} INFO - Started process 879 to run task
[2024-11-30T19:49:39.242+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fist_dag_v5', 'third_task', 'manual__2024-11-30T19:49:36.293888+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpyrpehlim']
[2024-11-30T19:49:39.246+0000] {standard_task_runner.py:105} INFO - Job 19: Subtask third_task
[2024-11-30T19:49:39.360+0000] {task_command.py:467} INFO - Running <TaskInstance: fist_dag_v5.third_task manual__2024-11-30T19:49:36.293888+00:00 [running]> on host ba06481f48a9
[2024-11-30T19:49:39.649+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='fist_dag_v5' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2024-11-30T19:49:36.293888+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-30T19:49:36.293888+00:00'
[2024-11-30T19:49:39.656+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-30T19:49:39.703+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-11-30T19:49:39.707+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello, i am task3 and will be running after task1!']
[2024-11-30T19:49:39.738+0000] {subprocess.py:99} INFO - Output:
[2024-11-30T19:49:39.758+0000] {subprocess.py:106} INFO - hello, i am task3 and will be running after task1!
[2024-11-30T19:49:39.760+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2024-11-30T19:49:39.845+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-30T19:49:39.859+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=fist_dag_v5, task_id=third_task, run_id=manual__2024-11-30T19:49:36.293888+00:00, execution_date=20241130T194936, start_date=20241130T194939, end_date=20241130T194939
[2024-11-30T19:49:39.965+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-30T19:49:40.028+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-30T19:49:40.047+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
