[2025-03-29T14:56:54.140+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-29T14:56:54.365+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fist_dag_using_python_operator_v06.get_name scheduled__2025-01-20T00:00:00+00:00 [queued]>
[2025-03-29T14:56:54.473+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fist_dag_using_python_operator_v06.get_name scheduled__2025-01-20T00:00:00+00:00 [queued]>
[2025-03-29T14:56:54.475+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-03-29T14:56:54.572+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): get_name> on 2025-01-20 00:00:00+00:00
[2025-03-29T14:56:54.618+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=903) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-29T14:56:54.623+0000] {standard_task_runner.py:72} INFO - Started process 918 to run task
[2025-03-29T14:56:54.657+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fist_dag_using_python_operator_v06', 'get_name', 'scheduled__2025-01-20T00:00:00+00:00', '--job-id', '334', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_with_python_operator.py', '--cfg-path', '/tmp/tmpsjge2t6e']
[2025-03-29T14:56:54.693+0000] {standard_task_runner.py:105} INFO - Job 334: Subtask get_name
[2025-03-29T14:56:55.250+0000] {task_command.py:467} INFO - Running <TaskInstance: fist_dag_using_python_operator_v06.get_name scheduled__2025-01-20T00:00:00+00:00 [running]> on host ba06481f48a9
[2025-03-29T14:56:56.194+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ARest' AIRFLOW_CTX_DAG_ID='fist_dag_using_python_operator_v06' AIRFLOW_CTX_TASK_ID='get_name' AIRFLOW_CTX_EXECUTION_DATE='2025-01-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-20T00:00:00+00:00'
[2025-03-29T14:56:56.199+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-29T14:56:56.434+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-29T14:56:56.503+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-29T14:56:56.506+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=fist_dag_using_python_operator_v06, task_id=get_name, run_id=scheduled__2025-01-20T00:00:00+00:00, execution_date=20250120T000000, start_date=20250329T145654, end_date=20250329T145656
[2025-03-29T14:56:56.646+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-29T14:56:56.755+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-29T14:56:56.838+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
