[2025-03-29T14:56:31.564+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-29T14:56:31.656+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fist_dag_v5.first_task scheduled__2025-01-08T00:00:00+00:00 [queued]>
[2025-03-29T14:56:31.723+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fist_dag_v5.first_task scheduled__2025-01-08T00:00:00+00:00 [queued]>
[2025-03-29T14:56:31.728+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-03-29T14:56:32.024+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): first_task> on 2025-01-08 00:00:00+00:00
[2025-03-29T14:56:32.048+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=628) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-29T14:56:32.065+0000] {standard_task_runner.py:72} INFO - Started process 643 to run task
[2025-03-29T14:56:32.065+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fist_dag_v5', 'first_task', 'scheduled__2025-01-08T00:00:00+00:00', '--job-id', '259', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpyyupetr5']
[2025-03-29T14:56:32.104+0000] {standard_task_runner.py:105} INFO - Job 259: Subtask first_task
[2025-03-29T14:56:32.364+0000] {task_command.py:467} INFO - Running <TaskInstance: fist_dag_v5.first_task scheduled__2025-01-08T00:00:00+00:00 [running]> on host ba06481f48a9
[2025-03-29T14:56:32.922+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='fist_dag_v5' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-08T00:00:00+00:00'
[2025-03-29T14:56:32.925+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-29T14:56:33.102+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-29T14:56:33.123+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello world, this is the first task!']
[2025-03-29T14:56:33.192+0000] {subprocess.py:99} INFO - Output:
[2025-03-29T14:56:33.200+0000] {subprocess.py:106} INFO - hello world, this is the first task!
[2025-03-29T14:56:33.209+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-29T14:56:33.410+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-29T14:56:33.412+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=fist_dag_v5, task_id=first_task, run_id=scheduled__2025-01-08T00:00:00+00:00, execution_date=20250108T000000, start_date=20250329T145631, end_date=20250329T145633
[2025-03-29T14:56:33.926+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-29T14:56:34.059+0000] {taskinstance.py:3895} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2025-03-29T14:56:34.128+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
